import { redirect } from "next/navigation";
import { requirePortalContext } from "@/lib/auth";

export const metadata = { title: "Notifications" };

/** Business notifications are generated by backend events, never manually. */
export default async function AdminCreateNotificationPage() {
  await requirePortalContext(["owner", "admin", "manager"]);
  redirect("/admin/notifications");
}