"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

async function refresh() { revalidatePath("/admin/settings"); revalidatePath("/admin/finance/income/new"); revalidatePath("/admin/finance/expenses/new"); }
export async function updateBranchAction(formData: FormData) { const profile = await requireUser(["admin", "manager"]); const sb = await createClient(); const branch = { name: String(formData.get("name") ?? ""), city: String(formData.get("city") ?? "") || null, address: String(formData.get("address") ?? "") || null, phone: String(formData.get("phone") ?? "") || null }; const { error } = await sb.from("branches").update(branch).eq("id", profile.branch_id); if (error) throw new Error(error.message); const { error: settingsError } = await sb.from("finance_settings").upsert({ branch_id: profile.branch_id, gstin: String(formData.get("gstin") ?? "") || null, fiscal_year_start_month: Number(formData.get("fiscal_year_start_month") ?? 4), updated_by: profile.id }, { onConflict: "branch_id" }); if (settingsError) throw new Error(settingsError.message); refresh(); }
export async function addCategoryAction(formData: FormData) { const profile = await requireUser(["admin", "manager"]); const table = String(formData.get("kind")) === "expense" ? "expense_categories" : "income_categories"; const sb = await createClient(); const { error } = await sb.from(table).insert({ branch_id: profile.branch_id, name: String(formData.get("name") ?? ""), code: String(formData.get("code") ?? "") || null, status: "active", is_system: false, created_by: profile.id, updated_by: profile.id }); if (error) throw new Error(error.message); refresh(); }
export async function deactivateCategoryAction(formData: FormData) { await requireUser(["admin", "manager"]); const table = String(formData.get("kind")) === "expense" ? "expense_categories" : "income_categories"; const sb = await createClient(); const { error } = await sb.from(table).update({ status: "inactive" }).eq("id", String(formData.get("id"))); if (error) throw new Error(error.message); refresh(); }
