"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const revenue = [{ m: "Jan", v: 112000 }, { m: "Feb", v: 128000 }, { m: "Mar", v: 121000 }, { m: "Apr", v: 149000 }, { m: "May", v: 157000 }, { m: "Jun", v: 181000 }];
const attendance = [{ d: "Mon", v: 78 }, { d: "Tue", v: 94 }, { d: "Wed", v: 86 }, { d: "Thu", v: 108 }, { d: "Fri", v: 102 }, { d: "Sat", v: 134 }, { d: "Sun", v: 64 }];
const plans = [{ name: "Monthly", value: 38, color: "#ff3024" }, { name: "Quarterly", value: 25, color: "#52c7ea" }, { name: "Half-yearly", value: 21, color: "#22b978" }, { name: "Annual", value: 16, color: "#f4b844" }];

export function DashboardCharts() { return <div className="grid gap-4 xl:grid-cols-3">
  <Card className="xl:col-span-2"><CardHeader><CardTitle>Revenue overview</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff3024" stopOpacity={.35}/><stop offset="1" stopColor="#ff3024" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.2}/><XAxis dataKey="m" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false} width={45}/><Tooltip formatter={(v) => `₹${Number(v).toLocaleString("en-IN")}`}/><Area type="monotone" dataKey="v" stroke="#ff3024" strokeWidth={3} fill="url(#rev)"/></AreaChart></ResponsiveContainer></CardContent></Card>
  <Card><CardHeader><CardTitle>Subscription distribution</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="75%"><PieChart><Pie data={plans} dataKey="value" innerRadius={55} outerRadius={82} paddingAngle={3}>{plans.map((p) => <Cell key={p.name} fill={p.color}/>)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="grid grid-cols-2 gap-2">{plans.map((p) => <span key={p.name} className="text-xs text-muted-foreground"><i className="mr-2 inline-block size-2 rounded-full" style={{ background: p.color }}/>{p.name}</span>)}</div></CardContent></Card>
  <Card className="xl:col-span-3"><CardHeader><CardTitle>Weekly attendance</CardTitle></CardHeader><CardContent className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={attendance}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.2}/><XAxis dataKey="d" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="v" fill="#52c7ea" radius={[6,6,0,0]} maxBarSize={42}/></BarChart></ResponsiveContainer></CardContent></Card>
  </div>; }
