/**
 * Notification types backed by a real database event or scheduled business reminder.
 *
 * This list MUST stay in sync with:
 *   - The notifications_business_type_check constraint in migrations 0023/0024
 *   - The queue_branch_notification() and queue_business_notification() DB functions
 *   - The generate_membership_reminders() cron function
 *
 * Every type here is generated by a real DB trigger or server-side cron —
 * never by the frontend.
 */
export const BUSINESS_NOTIFICATION_TYPES = [
  // ── Membership lifecycle ──────────────────────────────────────────────────
  "membership_created",
  "membership_renewed",
  "membership_expired",
  "membership_expiring_today",
  "membership_expiry_reminder",
  "membership_renewal_reminder",
  // ── Payments ─────────────────────────────────────────────────────────────
  "pending_balance",
  "payment_pending",
  "payment_received",
  "payment_failed",
  // ── Attendance ────────────────────────────────────────────────────────────
  "attendance_recorded",
  // ── Members ───────────────────────────────────────────────────────────────
  "member_created",
  // ── Infrastructure ────────────────────────────────────────────────────────
  "machine_connected",
  "machine_disconnected",
  "tenant_registered",
] as const;

export type BusinessNotificationType = (typeof BUSINESS_NOTIFICATION_TYPES)[number];

export function isBusinessNotificationType(value: unknown): value is BusinessNotificationType {
  return typeof value === "string" && (BUSINESS_NOTIFICATION_TYPES as readonly string[]).includes(value);
}
