"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { AssignedMember } from "@/services/trainer-portal.service";

type Workout = { id: string; name: string; exercise_name: string; sets: number | null; reps: number | null; weight_kg: number | null; cardio_minutes: number | null; rest_seconds: number | null; trainer_notes: string | null; scheduled_date: string | null; status: string; member_id: string };
export function WorkoutEditForm({ workout, members }: { workout: Workout; members: AssignedMember[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const payload: Record<string, unknown> = {}; for (const [key, value] of form.entries()) { if (value !== "") payload[key] = ["sets","reps","weight_kg","cardio_minutes","rest_seconds"].includes(key) ? Number(value) : value; } try { const response = await fetch(`/api/workouts/${workout.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to update workout"); router.push("/trainer/workouts"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update workout"); } finally { setPending(false); } }
  async function archive() { if (!window.confirm("Archive this workout? It will no longer appear as active.")) return; setPending(true); const response = await fetch(`/api/workouts/${workout.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "inactive" }) }); if (!response.ok) setError((await response.json()).error ?? "Unable to archive workout"); else { router.push("/trainer/workouts"); router.refresh(); } setPending(false); }
  return <form onSubmit={submit} className="space-y-5">{error && <p className="text-sm text-destructive">{error}</p>}<label className="block text-sm font-medium">Member<select name="member_id" defaultValue={workout.member_id} className="mt-1.5 h-10 w-full rounded-lg border bg-background px-3" required>{members.map((m) => <option key={m.id} value={m.id}>{m.full_name} ({m.member_code})</option>)}</select></label><div className="grid gap-4 md:grid-cols-2">{([["name","Name",workout.name,"text"],["exercise_name","Exercise",workout.exercise_name,"text"],["sets","Sets",workout.sets,"number"],["reps","Reps",workout.reps,"number"],["weight_kg","Weight (kg)",workout.weight_kg,"number"],["cardio_minutes","Cardio minutes",workout.cardio_minutes,"number"],["rest_seconds","Rest seconds",workout.rest_seconds,"number"],["scheduled_date","Scheduled date",workout.scheduled_date,"date"]] as const).map(([name,label,value,type]) => <label key={name} className="text-sm font-medium">{label}<Input className="mt-1.5" name={name} type={type} defaultValue={value ?? ""} min={type === "number" ? 0 : undefined} required={name === "name" || name === "exercise_name"} /></label>)}</div><label className="block text-sm font-medium">Notes<textarea name="trainer_notes" defaultValue={workout.trainer_notes ?? ""} className="mt-1.5 min-h-24 w-full rounded-lg border bg-background p-3" /></label><div className="flex justify-between"><Button type="button" variant="destructive" onClick={archive} disabled={pending}>Archive</Button><Button type="submit" disabled={pending}>Save changes</Button></div></form>;
}