import { notFound } from "next/navigation";
import { Bell, CalendarDays, ChartNoAxesCombined, Dumbbell, Gauge, ShieldCheck, UserRoundCog, UsersRound, Utensils, Wrench } from "lucide-react";
import { ModuleOverview, type ModuleConfig } from "@/components/modules/module-overview";

const modules: Record<string, ModuleConfig> = {
  memberships:   { title: "Memberships",    description: "Configure plans, activate subscriptions, and manage renewals.", icon: ShieldCheck,        action: "Create plan",       features: [{ title: "Flexible plans",    description: "Offer 1–12 month plans with GST, discounts, and features." }, { title: "Automatic dates",  description: "Calculate subscription end dates consistently." }, { title: "Renewal history",  description: "Preserve a full audit trail for renewals." }] },
  appointments:  { title: "Appointments",   description: "Coordinate member sessions with trainers and professionals.", icon: CalendarDays,       action: "Book appointment",  features: [{ title: "Trainer sessions", description: "Schedule one-to-one trainer sessions." },           { title: "Consultations",   description: "Book dietician and physiotherapist visits." },     { title: "Status workflow",  description: "Track pending → approved → completed." }] },
  trainers:      { title: "Trainers",       description: "Manage profiles, specializations, schedules, and members.", icon: UserRoundCog,      action: "Add trainer",       features: [{ title: "Trainer profiles", description: "Store experience, certifications, and specialization." }, { title: "Assignments",     description: "Connect members with trainers." },                { title: "Schedules",        description: "View appointments and workout duties." }] },
  workouts:      { title: "Workouts",       description: "Build structured programs and assign them to members.", icon: Dumbbell,           action: "Create workout",    features: [{ title: "Exercise library", description: "Organize exercises into categories." },               { title: "Training details", description: "Configure sets, reps, weight, cardio, and rest." }, { title: "Trainer notes",    description: "Record and adapt plans over time." }] },
  "diet-plans":  { title: "Diet plans",     description: "Create practical meal and macro plans for members.", icon: Utensils,            action: "Create diet plan",  features: [{ title: "Daily meals",      description: "Plan breakfast, lunch, dinner, and snacks." },         { title: "Macros",           description: "Track calories, protein, carbs, fat, and water." },  { title: "Member access",    description: "Members see only their assigned plan." }] },
  progress:      { title: "Progress",       description: "Measure outcomes with consistent monthly check-ins.", icon: Gauge,               action: "Record progress",   features: [{ title: "Body metrics",     description: "Capture weight, BMI, fat %, and measurements." },      { title: "Photos",           description: "Store private progress images securely." },          { title: "Trend charts",     description: "Visualize and celebrate measurable gains." }] },
  staff:         { title: "Staff",          description: "Manage reception, trainers, managers, and admins.", icon: UsersRound,          action: "Add staff",         features: [{ title: "Roles",            description: "Apply least-privilege access per role." },              { title: "Attendance",       description: "Track presence and leave balances." },                { title: "Compensation",     description: "Maintain salary information securely." }] },
  equipment:     { title: "Equipment",      description: "Keep every machine safe, available, and maintained.", icon: Wrench,             action: "Add equipment",     features: [{ title: "Asset register",   description: "Track serial number, purchase date, warranty." },       { title: "Maintenance",      description: "Plan service dates and receive alerts." },            { title: "History",          description: "Record vendors, costs, and work done." }] },
  reports:       { title: "Reports",        description: "Turn operational data into decisions and exports.", icon: ChartNoAxesCombined,  action: "Generate report",   features: [{ title: "Revenue",          description: "Analyze collections and payment channels." },           { title: "Members",          description: "Understand retention, growth, and visits." },         { title: "Operations",       description: "Report on trainers and appointments." }] },
  notifications: { title: "Notifications", description: "Manage system alerts and multi-channel comms.", icon: Bell,                  action: "New notification",  features: [{ title: "Expiry reminders", description: "Automated alerts at 15, 7, 3, and 1 days." },          { title: "Alerts",           description: "Payment, appointment, and birthday reminders." },    { title: "Channels",         description: "Dashboard, email, SMS, and WhatsApp." }] },
};

export default async function AdminModulePage({ params }: { params: Promise<{ module: string }> }) {
  const slug = (await params).module;
  const config = modules[slug];
  if (!config) notFound();
  const actionHref = slug === "reports" ? "/api/reports?resource=members" : `/admin/${slug}/new`;
  return <ModuleOverview config={config} actionHref={actionHref} />;
}
