"use client";

import { useMemo, useRef, useState } from "react";
import { CircleHelp, Download, FileSpreadsheet, LoaderCircle, Upload } from "lucide-react";
import { toast } from "sonner";
import { importOhlcAction, previewOhlcImportAction, type OhlcImportResult } from "@/app/actions/ohlc-import-actions";
import { autoDetectMapping, errorReport, missingRequired, parseAllSpreadsheetRows, parseSpreadsheet, validateOhlcRows, type ImportOptions, type OhlcError, type OhlcField, type OhlcMapping, type SpreadsheetData } from "@/lib/market-data/ohlc-import";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

const fieldLabels: Record<OhlcField, string> = { auto: "Auto Detect", ignore: "Ignore", symbol: "Symbol", date: "Date", open: "Open", high: "High", low: "Low", close: "Close", volume: "Volume", instrumentName: "Instrument Name" };
const defaults: ImportOptions = { logErrors: true, addSymbols: true, calculateComposites: false, noQuotationData: false, allowNegativePrices: false };
const optionEntries: Array<[keyof ImportOptions, string]> = [["logErrors", "Log errors"], ["addSymbols", "Automatically add new symbols"], ["calculateComposites", "Calculate composites"], ["noQuotationData", "No quotation data"], ["allowNegativePrices", "Allow negative prices"]];
type Branch = { id: string; name: string };

export function OhlcImportDialog({ branches, defaultBranchId }: { branches: Branch[]; defaultBranchId?: string | null }) {
  const [open, setOpen] = useState(false); const [step, setStep] = useState<"upload" | "define" | "validate" | "result">("upload");
  const [file, setFile] = useState<File | null>(null); const [buffer, setBuffer] = useState<ArrayBuffer | null>(null); const [data, setData] = useState<SpreadsheetData | null>(null);
  const [mapping, setMapping] = useState<OhlcMapping>({}); const [branchId, setBranchId] = useState(defaultBranchId ?? ""); const [separator, setSeparator] = useState(","); const [skipFirst, setSkipFirst] = useState(0); const [options, setOptions] = useState(defaults);
  const [errors, setErrors] = useState<OhlcError[]>([]); const [ready, setReady] = useState(0); const [pending, setPending] = useState(false); const [result, setResult] = useState<OhlcImportResult | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  const missing = useMemo(() => missingRequired(mapping), [mapping]); const isCsv = file?.name.toLowerCase().endsWith(".csv") ?? false;

  function reset() { setStep("upload"); setFile(null); setBuffer(null); setData(null); setMapping({}); setSeparator(","); setSkipFirst(0); setOptions(defaults); setErrors([]); setReady(0); setResult(null); if (inputRef.current) inputRef.current.value = ""; }
  async function loadFile(next: File, nextWorksheet?: string, nextSeparator = separator, nextSkip = skipFirst) {
    if (next.size > 10 * 1024 * 1024) { toast.error("The file must be 10 MB or smaller."); return; }
    try { const nextBuffer = buffer && file === next ? buffer : await next.arrayBuffer(); const parsed = parseSpreadsheet(nextBuffer, next.name, nextWorksheet, nextSeparator, nextSkip); setFile(next); setBuffer(nextBuffer); setData(parsed); setMapping(autoDetectMapping(parsed.columns)); } catch { toast.error("We could not read this spreadsheet. Upload a valid .xlsx, .xls, or .csv file."); }
  }
  async function reparse(nextWorksheet = data?.worksheet, nextSeparator = separator, nextSkip = skipFirst) { if (file) await loadFile(file, nextWorksheet, nextSeparator, nextSkip); }
  function updateOption(key: keyof ImportOptions) { setOptions((current) => ({ ...current, [key]: !current[key] })); }
  function continueToDefine() {
    if (!data || !data.rawHeaders.length) { toast.error("No column headers were detected."); return; }
    if (!data.rawRows.length) { toast.error("No data rows were found in the selected worksheet."); return; }
    setStep("define");
  }
  async function validate() {
    if (!file || !buffer || !data || missing.length) return;
    setPending(true);
    try { const all = parseAllSpreadsheetRows(buffer, file.name, data.worksheet, separator, skipFirst); if (all.rows.length > 10_000) return toast.error("Import up to 10,000 rows at a time."); const validated = validateOhlcRows(all.rows, all.rowOffset, mapping, options); const preview = await previewOhlcImportAction({ branchId, candidates: validated.candidates, options }); if (preview.error) return toast.error(preview.error); setReady(preview.ready); setErrors([...validated.errors, ...preview.errors]); setStep("validate"); } catch { toast.error("We could not parse the selected worksheet."); } finally { setPending(false); }
  }
  async function importData() {
    if (!file || !buffer || !data) return; setPending(true);
    try { const all = parseAllSpreadsheetRows(buffer, file.name, data.worksheet, separator, skipFirst); const validated = validateOhlcRows(all.rows, all.rowOffset, mapping, options); const response = await importOhlcAction({ branchId, candidates: validated.candidates, validationErrors: validated.errors, options }); if (response.error) toast.error(response.error); else { setResult(response); setErrors(response.errors); setStep("result"); } } catch { toast.error("The import could not be completed."); } finally { setPending(false); }
  }
  function downloadErrors() { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([errorReport(errors)], { type: "text/csv;charset=utf-8" })); link.download = "ohlc-import-errors.csv"; link.click(); URL.revokeObjectURL(link.href); }

  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); if (!next) reset(); }}>
    <DialogTrigger asChild><Button type="button" variant="outline" size="sm"><Upload className="size-4" />Import OHLC</Button></DialogTrigger>
    <DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle className="flex items-center gap-2"><FileSpreadsheet className="size-5 text-primary" />OHLC data import</DialogTitle><DialogDescription>Upload file ? Define fields ? Preview data ? Validate ? Import</DialogDescription></DialogHeader>
      {step === "upload" && <div className="space-y-5"><label className="block space-y-1.5 text-sm font-medium">Data file (.xlsx, .xls, .csv)<input ref={inputRef} type="file" accept=".xlsx,.xls,.csv" className="mt-1 block w-full rounded-lg border bg-background p-2 text-sm" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) void loadFile(selected); }} /></label><p className="text-xs text-muted-foreground">Maximum 10,000 rows and 10 MB. No data is imported until you confirm the final step.</p><label className="block space-y-1.5 text-sm font-medium">Branch<select value={branchId} onChange={(event) => setBranchId(event.target.value)} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Select branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label>{data && <div className="rounded-lg border bg-muted/20 p-3 text-sm"><p className="font-medium">{file?.name}</p><p className="text-muted-foreground">{data.columns.length} columns and {data.rawRows.length} data rows detected in {data.worksheet} (header row {data.headerRowIndex + 1}).</p><ol className="mt-2 grid list-decimal grid-cols-2 gap-x-6 gap-y-1 pl-5 text-xs sm:grid-cols-4">{data.rawHeaders.map((column, index) => <li key={`${column}-${index}`} className="truncate" title={column}>{column}</li>)}</ol></div>}</div>}
      {step === "define" && data && <div className="space-y-5"><div><h2 className="text-xl font-semibold">Define fields</h2><p className="mt-1 text-sm text-muted-foreground">Here you can define the fields in the data file. Use combo-boxes to select appropriate field types.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.columns.map((column, index) => <label key={`${column}-${index}`} className="rounded-lg border p-3 text-sm font-medium"><span className="block text-muted-foreground">Column {index + 1}</span><span className="mt-1 block truncate" title={column}>{column}</span><select value={mapping[index] ?? "auto"} onChange={(event) => setMapping((current) => ({ ...current, [index]: event.target.value as OhlcField }))} className="mt-2 h-10 w-full rounded-md border bg-background px-2 text-sm">{Object.entries(fieldLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>)}</div>
        {isCsv && <div className="grid gap-3 rounded-lg border bg-muted/20 p-4 sm:grid-cols-2"><label className="text-sm font-medium">Separator<select value={separator} onChange={(event) => { setSeparator(event.target.value); void reparse(data.worksheet, event.target.value, skipFirst); }} className="mt-1 h-10 w-full rounded-md border bg-background px-2"><option value=",">Comma (,)</option><option value=";">Semicolon (;)</option><option value={"\t"}>Tab</option><option value="|">Pipe (|)</option></select></label><label className="text-sm font-medium">Skip first<input type="number" min="0" value={skipFirst} onChange={(event) => { const value = Math.max(0, Number(event.target.value)); setSkipFirst(value); void reparse(data.worksheet, separator, value); }} className="mt-1 h-10 w-full rounded-md border bg-background px-2" /> lines</label></div>}
        {!isCsv && data.worksheets.length > 1 && <label className="block max-w-sm text-sm font-medium">Worksheet<select value={data.worksheet} onChange={(event) => void reparse(event.target.value)} className="mt-1 h-10 w-full rounded-md border bg-background px-2">{data.worksheets.map((sheet) => <option key={sheet}>{sheet}</option>)}</select></label>}
        <fieldset className="rounded-lg border p-4"><legend className="px-1 text-sm font-semibold">Options</legend><div className="grid gap-2 text-sm sm:grid-cols-2">{optionEntries.map(([key, label]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={options[key]} onChange={() => updateOption(key)} />{label}</label>)}</div></fieldset>
        {missing.length > 0 && <div className="rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"><p className="font-medium">Required OHLC fields are not mapped.</p><p>Missing: {missing.map((field) => fieldLabels[field]).join(", ")}</p></div>}
        <div><h3 className="font-semibold">Data file sample</h3><div className="mt-2 overflow-x-auto rounded-lg border"><table className="w-full text-left text-xs"><thead className="bg-muted"><tr>{data.columns.map((column, index) => <th key={`${column}-${index}`} className="whitespace-nowrap px-3 py-2">{column}</th>)}</tr></thead><tbody>{data.rows.slice(0, 10).map((row, index) => <tr key={index} className="border-t">{data.columns.map((_, columnIndex) => <td key={columnIndex} className="whitespace-nowrap px-3 py-2">{String(row[columnIndex] ?? "")}</td>)}</tr>)}</tbody></table></div></div></div>}
      {step === "validate" && <div className="space-y-5"><div><h2 className="text-xl font-semibold">Validate import</h2><p className="text-sm text-muted-foreground">Review the validation summary before inserting any data.</p></div><div className="grid gap-3 sm:grid-cols-4"><Summary label="Total Rows" value={ready + errors.length} /><Summary label="Ready to Import" value={ready} tone="success" /><Summary label="Duplicates" value={errors.filter((error) => error.error.includes("Duplicate")).length} tone="warning" /><Summary label="Errors" value={errors.length} tone="danger" /></div>{errors.length > 0 && <ErrorList errors={errors} />}</div>}
      {step === "result" && result && <div className="space-y-4"><div><h2 className="text-xl font-semibold">Import Complete</h2><p className="mt-2 text-sm text-emerald-700">? {result.imported.toLocaleString()} OHLC records imported</p><p className="text-sm text-muted-foreground">? {result.duplicates.toLocaleString()} duplicate records skipped</p><p className="text-sm text-amber-700">? {result.errors.length.toLocaleString()} records failed</p></div>{result.errors.length > 0 && <ErrorList errors={result.errors} />}</div>}
      <DialogFooter className="mt-2"><Button type="button" variant="ghost" onClick={() => step === "upload" ? setOpen(false) : setStep(step === "define" ? "upload" : "define")}>{step === "upload" ? "Cancel" : "Back"}</Button><Button type="button" variant="ghost" title="Upload a file, map its columns, validate, then import."><CircleHelp className="size-4" />Help</Button>{step === "upload" && <Button type="button" disabled={!data || !branchId} onClick={continueToDefine}>Next</Button>}{step === "define" && <Button type="button" disabled={missing.length > 0} onClick={() => void validate()}>{pending && <LoaderCircle className="size-4 animate-spin" />}Next</Button>}{step === "validate" && <Button type="button" disabled={pending || !ready} onClick={() => void importData()}>{pending && <LoaderCircle className="size-4 animate-spin" />}Import Data</Button>}{step === "result" && <>{errors.length > 0 && <Button type="button" variant="outline" onClick={() => document.getElementById("ohlc-import-errors")?.scrollIntoView({ behavior: "smooth" })}>View Errors</Button>}<Button type="button" variant="outline" disabled={!errors.length} onClick={downloadErrors}><Download className="size-4" />Download Error Report</Button><Button type="button" onClick={reset}>Import Another File</Button></>}</DialogFooter></DialogContent></Dialog>;
}
function Summary({ label, value, tone }: { label: string; value: number; tone?: "success" | "warning" | "danger" }) { return <div className={`rounded-lg border p-3 ${tone === "success" ? "bg-emerald-500/10" : tone === "warning" ? "bg-amber-500/10" : tone === "danger" ? "bg-destructive/10" : ""}`}><p className="text-xs text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value.toLocaleString()}</p></div>; }
function ErrorList({ errors }: { errors: OhlcError[] }) { return <div id="ohlc-import-errors" className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-sm"><div className="flex items-center justify-between"><p className="font-medium">Row-level errors</p>{errors.length > 10 && <p className="text-xs">Showing first 10 of {errors.length}</p>}</div><ul className="mt-2 space-y-1">{errors.slice(0, 10).map((error, index) => <li key={`${error.row}-${error.error}-${index}`}>Row {error.row}{error.symbol ? ` (${error.symbol})` : ""}: {error.error}</li>)}</ul></div>; }