-- Corrective follow-up to 0023: record-driven business events and strict RLS.
begin;
alter table public.notifications add column if not exists target_roles text[] not null default '{}'::text[];
alter table public.notifications add column if not exists updated_at timestamptz not null default now();
alter table public.notifications enable row level security;
drop policy if exists notifications_insert on public.notifications;
drop policy if exists notifications_update on public.notifications;
drop policy if exists notifications_delete on public.notifications;
drop policy if exists notifications_manage on public.notifications;
drop policy if exists notifications_read on public.notifications;
create policy notifications_read on public.notifications for select to authenticated using ((user_id=auth.uid() and tenant_id=public.current_tenant_id()) or (user_id is null and branch_id=public.current_branch_id() and tenant_id=public.current_tenant_id() and public.notification_role_is_allowed(target_roles)) or (public.is_super_admin() and tenant_id is null and public.notification_role_is_allowed(target_roles)));
create or replace function public.queue_business_notification(p_branch_id uuid,p_tenant_id uuid,p_user_id uuid,p_member_id uuid,p_type text,p_title text,p_message text,p_entity_type text,p_entity_id uuid,p_roles text[],p_fingerprint text,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path=public as $$
declare v_branch_tenant uuid; v_allowed_roles constant text[]:=array['owner','admin','manager','reception','trainer','dietician','diet-planner','diet_planner','member','super_admin']; begin select tenant_id into v_branch_tenant from public.branches where id=p_branch_id; if v_branch_tenant is null or v_branch_tenant is distinct from p_tenant_id then raise exception 'Notification branch tenant mismatch'; end if; if p_entity_id is null or nullif(trim(p_fingerprint),'') is null or p_roles is null or cardinality(p_roles)=0 or not(p_roles <@ v_allowed_roles) or length(trim(coalesce(p_title,'')))<2 or length(trim(coalesce(p_message,'')))<2 then raise exception 'Invalid business notification payload'; end if; insert into public.notifications(branch_id,tenant_id,user_id,member_id,type,title,message,channels,target_roles,metadata,scheduled_for) values(p_branch_id,p_tenant_id,p_user_id,p_member_id,p_type,p_title,p_message,array['dashboard']::public.notification_channel[],p_roles,coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object('fingerprint',p_fingerprint,'entity_type',p_entity_type,'entity_id',p_entity_id),now()) on conflict do nothing; end $$;
-- Runs from the protected server cron route (or pg_cron where configured).
create or replace function public.generate_membership_reminders() returns integer language plpgsql security definer set search_path=public as $$
declare r record; d integer; c integer:=0; typ text; ttl text; msg text; begin for r in select s.id,s.member_id,s.branch_id,s.tenant_id,s.end_date,m.full_name,m.user_id from public.subscriptions s join public.members m on m.id=s.member_id where s.status='active' and s.end_date in(current_date,current_date+2,current_date+8,current_date+15,current_date+60) loop d:=r.end_date-current_date; typ:=case when d=0 then 'membership_expiring_today' else 'membership_expiry_reminder' end; ttl:=case when d=0 then 'Membership expires today' else format('Membership expires in %s days',d) end; msg:=case when d=0 then format('%s''s membership expires today.',r.full_name) else format('%s''s membership expires in %s days (%s).',r.full_name,d,to_char(r.end_date,'DD Mon YYYY')) end; perform public.queue_business_notification(r.branch_id,r.tenant_id,null,r.member_id,typ,ttl,msg,'subscription',r.id,array['owner','admin','manager','reception'],typ||':staff:'||r.id||':'||r.end_date,jsonb_build_object('subscription_id',r.id,'expiry_date',r.end_date,'remaining_days',d)); if r.user_id is not null then perform public.queue_business_notification(r.branch_id,r.tenant_id,r.user_id,r.member_id,typ,ttl,msg,'subscription',r.id,array['member'],typ||':member:'||r.id||':'||r.end_date,jsonb_build_object('subscription_id',r.id,'expiry_date',r.end_date,'remaining_days',d)); end if; c:=c+1; end loop; for r in select s.id,s.member_id,s.branch_id,s.tenant_id,s.end_date,m.full_name,m.user_id from public.subscriptions s join public.members m on m.id=s.member_id where s.status in('active','expired') and s.end_date<current_date loop perform public.queue_business_notification(r.branch_id,r.tenant_id,null,r.member_id,'membership_expired','Membership expired',format('%s''s membership expired on %s.',r.full_name,to_char(r.end_date,'DD Mon YYYY')),'subscription',r.id,array['owner','admin','manager','reception'],'membership_expired:staff:'||r.id||':'||r.end_date,jsonb_build_object('subscription_id',r.id,'expiry_date',r.end_date)); if r.user_id is not null then perform public.queue_business_notification(r.branch_id,r.tenant_id,r.user_id,r.member_id,'membership_expired','Membership expired',format('Your membership expired on %s. Please contact the gym to renew.',to_char(r.end_date,'DD Mon YYYY')),'subscription',r.id,array['member'],'membership_expired:member:'||r.id||':'||r.end_date,jsonb_build_object('subscription_id',r.id,'expiry_date',r.end_date)); end if; c:=c+1; end loop; return c; end $$;
create or replace function public.notify_invoice_balance() returns trigger language plpgsql security definer set search_path=public as $$
declare m record; balance numeric(12,2); begin balance:=new.total_amount-new.amount_paid; if new.status<>'void' and balance>0 then select full_name,user_id into m from public.members where id=new.member_id; perform public.queue_business_notification(new.branch_id,new.tenant_id,null,new.member_id,'pending_balance','Pending balance',format('%s has an outstanding balance of %s on invoice %s.',m.full_name,to_char(balance,'FM999G999G999D00'),new.invoice_number),'invoice',new.id,array['owner','admin','manager','reception'],'pending_balance:staff:'||new.id||':'||balance::text,jsonb_build_object('invoice_id',new.id,'invoice_number',new.invoice_number,'outstanding_balance',balance,'due_date',new.due_date)); if m.user_id is not null then perform public.queue_business_notification(new.branch_id,new.tenant_id,m.user_id,new.member_id,'pending_balance','Pending balance',format('Your outstanding balance is %s for invoice %s.',to_char(balance,'FM999G999G999D00'),new.invoice_number),'invoice',new.id,array['member'],'pending_balance:member:'||new.id||':'||balance::text,jsonb_build_object('invoice_id',new.id,'invoice_number',new.invoice_number,'outstanding_balance',balance,'due_date',new.due_date)); end if; end if; return new; end $$;
create or replace function public.notify_attendance_recorded() returns trigger language plpgsql security definer set search_path=public as $$
declare m record; begin select full_name,user_id into m from public.members where id=new.member_id; perform public.queue_business_notification(new.branch_id,new.tenant_id,null,new.member_id,'attendance_recorded','Attendance recorded',format('%s checked in at %s.',m.full_name,to_char(new.entry_time,'DD Mon YYYY HH24:MI')),'attendance',new.id,array['owner','admin','manager','reception'],'attendance_recorded:staff:'||new.id,jsonb_build_object('attendance_id',new.id,'attendance_date',new.attendance_date)); if m.user_id is not null then perform public.queue_business_notification(new.branch_id,new.tenant_id,m.user_id,new.member_id,'attendance_recorded','Attendance recorded',format('Your attendance was recorded at %s.',to_char(new.entry_time,'DD Mon YYYY HH24:MI')),'attendance',new.id,array['member'],'attendance_recorded:member:'||new.id,jsonb_build_object('attendance_id',new.id,'attendance_date',new.attendance_date)); end if; return new; end $$;
drop trigger if exists notifications_invoice_balance on public.invoices;
create trigger notifications_invoice_balance after insert or update of total_amount,amount_paid,status on public.invoices for each row execute function public.notify_invoice_balance();
drop trigger if exists notifications_attendance_recorded on public.attendance;
create trigger notifications_attendance_recorded after insert on public.attendance for each row execute function public.notify_attendance_recorded();
alter table public.notifications drop constraint if exists notifications_business_type_check;
alter table public.notifications add constraint notifications_business_type_check check(type=any(array['member_created','membership_created','membership_renewed','membership_expired','membership_expiring_today','membership_expiry_reminder','membership_renewal_reminder','pending_balance','payment_pending','payment_received','payment_failed','machine_connected','machine_disconnected','attendance_recorded','tenant_registered']::text[]));
create index if not exists notifications_tenant_role_unread_idx on public.notifications(tenant_id,branch_id,created_at desc) where read_at is null;
create index if not exists notifications_private_unread_idx on public.notifications(tenant_id,user_id,created_at desc) where read_at is null;
revoke all on function public.queue_business_notification(uuid,uuid,uuid,uuid,text,text,text,text,uuid,text[],text,jsonb) from public;
revoke all on function public.generate_membership_reminders() from public;
revoke all on function public.notify_invoice_balance() from public;
revoke all on function public.notify_attendance_recorded() from public;
alter table public.notifications replica identity full;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then alter publication supabase_realtime add table public.notifications; end if; end $$;
commit;grant execute on function public.generate_membership_reminders() to service_role;
